name: Build and Publish

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build-publish.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build-publish.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Metadata extraction job
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version and setup tags
        id: meta
        run: |
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-dev")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Determine tags to create
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          fi

          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION_TAG}"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
          echo "Tags: $TAGS"

  # Build and scan with matrix strategy (parallel execution)
  build-and-scan:
    needs: prepare
    strategy:
      matrix:
        arch:
          - name: amd64
            runner: ubuntu-latest
            nix-system: x86_64-linux
          - name: arm64
            runner: ubuntu-24.04-arm
            nix-system: aarch64-linux
    runs-on: ${{ matrix.arch.runner }}
    permissions:
      contents: read
      security-events: write # For SARIF upload

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Cache Trivy vulnerability database (saves ~30s per run)
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix cache
        uses: cachix/cachix-action@v16
        continue-on-error: true
        with:
          name: gitlab-runner-kubevirt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build ${{ matrix.arch.name }} image
        timeout-minutes: 30
        run: |
          echo "🏗️  Building ${{ matrix.arch.name }} image (native ${{ matrix.arch.nix-system }})..."
          nix build .#packages.${{ matrix.arch.nix-system }}.container \
            -o result-${{ matrix.arch.name }} \
            --print-build-logs \
            --keep-going
          echo "✓ ${{ matrix.arch.name }} build complete"
          ls -lh result-${{ matrix.arch.name }}

      # Security scanning (runs in parallel with other architecture)
      - name: Generate SBOM (${{ matrix.arch.name }})
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@0.33.1
        with:
          input: result-${{ matrix.arch.name }}
          format: "cyclonedx"
          output: "sbom-${{ matrix.arch.name }}.json"
          scan-type: "image"

      - name: Vulnerability scan SARIF (${{ matrix.arch.name }})
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@0.33.1
        with:
          input: result-${{ matrix.arch.name }}
          format: "sarif"
          output: "trivy-${{ matrix.arch.name }}.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"
          timeout: "10m"

      - name: Upload SARIF (${{ matrix.arch.name }})
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: "trivy-${{ matrix.arch.name }}.sarif"
          category: "container-scan-${{ matrix.arch.name }}"

      - name: Vulnerability scan table (${{ matrix.arch.name }})
        if: github.event_name != 'pull_request' && matrix.arch.name == 'amd64'
        uses: aquasecurity/trivy-action@0.33.1
        continue-on-error: true
        with:
          input: result-${{ matrix.arch.name }}
          format: "table"
          severity: "CRITICAL,HIGH"
          timeout: "10m"

      # Upload artifacts
      - name: Upload ${{ matrix.arch.name }} image
        uses: actions/upload-artifact@v5
        with:
          name: container-${{ matrix.arch.name }}
          path: result-${{ matrix.arch.name }}
          retention-days: 1

      - name: Upload ${{ matrix.arch.name }} SBOM
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v5
        with:
          name: sbom-${{ matrix.arch.name }}
          path: sbom-${{ matrix.arch.name }}.json
          retention-days: 90

  # Assemble multi-arch manifest and sign
  assemble-and-publish:
    needs: [prepare, build-and-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Download AMD64 artifact
        uses: actions/download-artifact@v5
        with:
          name: container-amd64
          path: .

      - name: Download ARM64 artifact
        uses: actions/download-artifact@v5
        with:
          name: container-arm64
          path: .

      - name: Download SBOMs
        if: github.event_name != 'pull_request'
        uses: actions/download-artifact@v5
        with:
          pattern: sbom-*
          path: sboms
          merge-multiple: true

      - name: Verify downloaded artifacts
        run: |
          echo "📦 Verifying downloaded artifacts..."
          ls -lh result-*
          file result-amd64 result-arm64

      - name: Setup buildah and container tools
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah skopeo

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        run: |
          buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: Create and push multi-arch manifest
        if: github.event_name != 'pull_request'
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          VERSION="${{ needs.prepare.outputs.version }}"

          echo "🔨 Creating multi-arch manifest..."
          buildah manifest create multiarch-manifest

          echo "📥 Loading AMD64 image..."
          AMD64_ID=$(buildah pull docker-archive:result-amd64)
          buildah manifest add --arch amd64 --os linux multiarch-manifest containers-storage:$AMD64_ID

          echo "📥 Loading ARM64 image..."
          ARM64_ID=$(buildah pull docker-archive:result-arm64)
          buildah manifest add --arch arm64 --os linux multiarch-manifest containers-storage:$ARM64_ID

          echo "🏷️  Adding OCI annotations to manifest..."
          buildah manifest annotate multiarch-manifest \
            --annotation "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --annotation "org.opencontainers.image.authors=thpham" \
            --annotation "org.opencontainers.image.url=https://github.com/${{ github.repository }}" \
            --annotation "org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md" \
            --annotation "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --annotation "org.opencontainers.image.version=$VERSION" \
            --annotation "org.opencontainers.image.revision=${{ github.sha }}" \
            --annotation "org.opencontainers.image.vendor=thpham" \
            --annotation "org.opencontainers.image.licenses=MIT" \
            --annotation "org.opencontainers.image.title=gitlab-runner-kubevirt" \
            --annotation "org.opencontainers.image.description=GitLab Runner executor for KubeVirt VMs"

          echo "🚀 Pushing multi-arch manifest to registry..."
          IFS=',' read -ra TAG_ARRAY <<< "${{ needs.prepare.outputs.tags }}"
          for tag in "${TAG_ARRAY[@]}"; do
            echo "  → $tag"
            buildah manifest push --all multiarch-manifest docker://$tag
          done

          echo "✓ Multi-arch images published successfully"

      - name: Verify multi-arch manifest
        if: github.event_name != 'pull_request'
        run: |
          echo "🔍 Inspecting multi-arch manifest..."
          buildah manifest inspect multiarch-manifest

          echo ""
          echo "🔍 Verifying registry manifest..."
          skopeo inspect docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}

      # Image signing and SBOM attestation
      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4.0.0

      - name: Sign multi-arch manifest
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # Sign all published tags (multi-arch manifests)
          IFS=',' read -ra TAG_ARRAY <<< "${{ needs.prepare.outputs.tags }}"
          for tag in "${TAG_ARRAY[@]}"; do
            echo "🔐 Signing multi-arch manifest: $tag"
            cosign sign --yes "$tag"
          done

      - name: Attach SBOMs to image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_REF="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}"

          echo "📎 Attaching AMD64 SBOM to $IMAGE_REF"
          cosign attach sbom --sbom sboms/sbom-amd64.json "$IMAGE_REF"

          echo "📎 Attaching ARM64 SBOM to $IMAGE_REF"
          cosign attach sbom --sbom sboms/sbom-arm64.json "$IMAGE_REF"

      - name: Upload SBOM reports
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v5
        with:
          name: sbom-reports
          path: sboms/*.json
          retention-days: 90
