name: Build and Publish

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build-publish.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build-publish.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Metadata extraction job to share version/tags across all jobs
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version and setup tags
        id: meta
        run: |
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-dev")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Determine tags to create
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          fi

          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION_TAG}"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
          echo "Tags: $TAGS"

  # Native AMD64 build
  build-amd64:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix cache
        uses: cachix/cachix-action@v16
        continue-on-error: true
        with:
          name: gitlab-runner-kubevirt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build AMD64 image
        timeout-minutes: 30
        run: |
          echo "🏗️  Building AMD64 image (native x86_64)..."
          nix build .#packages.x86_64-linux.container -o result-amd64 --print-build-logs --keep-going
          echo "✓ AMD64 build complete"
          ls -lh result-amd64

      - name: Upload AMD64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-amd64
          path: result-amd64
          retention-days: 1

  # Native ARM64 build
  build-arm64:
    needs: prepare
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix cache
        uses: cachix/cachix-action@v16
        continue-on-error: true
        with:
          name: gitlab-runner-kubevirt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build ARM64 image
        timeout-minutes: 30
        run: |
          echo "🏗️  Building ARM64 image (native aarch64)..."
          nix build .#packages.aarch64-linux.container -o result-arm64 --print-build-logs --keep-going
          echo "✓ ARM64 build complete"
          ls -lh result-arm64

      - name: Upload ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-arm64
          path: result-arm64
          retention-days: 1

  # Assemble multi-arch manifest and publish
  assemble-and-publish:
    needs: [prepare, build-amd64, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Download AMD64 artifact
        uses: actions/download-artifact@v4
        with:
          name: container-amd64
          path: .

      - name: Download ARM64 artifact
        uses: actions/download-artifact@v4
        with:
          name: container-arm64
          path: .

      - name: Verify downloaded artifacts
        run: |
          echo "📦 Verifying downloaded artifacts..."
          ls -lh result-*
          file result-amd64 result-arm64

      - name: Setup buildah and container tools
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah skopeo

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        run: |
          buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: Create and push multi-arch manifest
        if: github.event_name != 'pull_request'
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          VERSION="${{ needs.prepare.outputs.version }}"

          echo "🔨 Creating multi-arch manifest..."
          buildah manifest create multiarch-manifest

          echo "📥 Loading AMD64 image..."
          AMD64_ID=$(buildah pull docker-archive:result-amd64)
          buildah manifest add --arch amd64 --os linux multiarch-manifest containers-storage:$AMD64_ID

          echo "📥 Loading ARM64 image..."
          ARM64_ID=$(buildah pull docker-archive:result-arm64)
          buildah manifest add --arch arm64 --os linux multiarch-manifest containers-storage:$ARM64_ID

          echo "🚀 Pushing multi-arch manifest to registry..."
          IFS=',' read -ra TAG_ARRAY <<< "${{ needs.prepare.outputs.tags }}"
          for tag in "${TAG_ARRAY[@]}"; do
            echo "  → $tag"
            buildah manifest push --all multiarch-manifest docker://$tag
          done

          echo "✓ Multi-arch images published successfully"

      - name: Run security scan
        if: github.event_name != 'pull_request'
        continue-on-error: true
        run: |
          docker load < result-amd64
          docker scout cves ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }} || true

      - name: Verify multi-arch manifest
        if: github.event_name != 'pull_request'
        run: |
          echo "🔍 Inspecting multi-arch manifest..."
          buildah manifest inspect multiarch-manifest

          echo ""
          echo "🔍 Verifying registry manifest..."
          skopeo inspect docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}
